layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: lukeshorejones
  # medium: @your_username
  # stackoverflow: your_user_id
  twitter: lukeshorejones
  youtube: UCA4H-vgQ27OgAR_MB1QUizw

# topics:
#   - name: Python
#     web_url: https://github.com/topics/python
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
#   - name: Java
#     web_url: https://github.com/topics/java
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/java/java.png
#   - name: Haskell
#     web_url: https://github.com/topics/haskell
#     image_url: https://raw.githubusercontent.com/github/explore/a99873de88db54b274184fed1eebdb01da4dd92b/topics/haskell/haskell.png
#   - name: HTML & CSS
#     web_url: https://github.com/topics/html
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/html/html.png
